spring.application.name=products-app

# ============================================================
#  ETAPE 3 : Configuration de l'unite de persistance (H2)
# ============================================================
server.port=8085

# Base de donnees H2 en memoire
spring.datasource.url=jdbc:h2:mem:products-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 accessible sur http://localhost:8085/h2-console
spring.h2.console.enabled=true

# Hibernate cree/met a jour automatiquement les tables
spring.jpa.hibernate.ddl-auto=update

# Affiche les requetes SQL dans la console
spring.jpa.show-sql=true
